"""empty message

Revision ID: a206ceb03c48
Revises: 
Create Date: 2025-06-18 12:53:15.948915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a206ceb03c48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'utilisateur', ['ID_USER'], ['ID_USER'])

    with op.batch_alter_table('collection_recette', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'collection', ['ID_COLLECTION'], ['ID_COLLECTION'])
        batch_op.create_foreign_key(None, 'recette', ['ID_RECETTE'], ['ID_RECETTE'])

    with op.batch_alter_table('commentaire', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'recette', ['ID_RECETTE'], ['ID_RECETTE'])
        batch_op.create_foreign_key(None, 'utilisateur', ['ID_USER'], ['ID_USER'])

    with op.batch_alter_table('favoris', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'recette', ['ID_RECETTE'], ['ID_RECETTE'])
        batch_op.create_foreign_key(None, 'utilisateur', ['ID_USER'], ['ID_USER'])

    with op.batch_alter_table('historique_consultation', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'utilisateur', ['ID_USER'], ['ID_USER'])
        batch_op.create_foreign_key(None, 'recette', ['ID_RECETTE'], ['ID_RECETTE'])

    with op.batch_alter_table('historique_recherche', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'utilisateur', ['ID_USER'], ['ID_USER'])

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('NOTE',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'utilisateur', ['ID_USER'], ['ID_USER'])
        batch_op.create_foreign_key(None, 'recette', ['ID_RECETTE'], ['ID_RECETTE'])

    with op.batch_alter_table('preference_utilisateur', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'utilisateur', ['ID_USER'], ['ID_USER'])

    with op.batch_alter_table('recette', schema=None) as batch_op:
        batch_op.alter_column('regime_alimentaire',
               existing_type=mysql.SET('Végétarien', 'Végétalien', 'Sans gluten', 'Sans lactose', 'Paleo', 'Keto'),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'categorie', ['ID_CATEGORIE'], ['ID_CATEGORIE'])
        batch_op.create_foreign_key(None, 'utilisateur', ['ID_USER'], ['ID_USER'])

    with op.batch_alter_table('recette_ingredient', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'recette', ['ID_RECETTE'], ['ID_RECETTE'])
        batch_op.create_foreign_key(None, 'ingredient', ['ID_INGREDIENT'], ['ID_INGREDIENT'])

    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IS_ADMIN', sa.Boolean(), nullable=True))
        batch_op.alter_column('AVATAR',
               existing_type=mysql.VARCHAR(length=255),
               comment="Chemin vers l'image de profil",
               existing_comment='Chemin vers limage de profil',
               existing_nullable=True)
        batch_op.alter_column('BIO',
               existing_type=mysql.TEXT(),
               comment="Description de l'utilisateur",
               existing_comment='Description de l utilisateur',
               existing_nullable=True)
        batch_op.alter_column('REGIME_ALIMENTAIRE',
               existing_type=mysql.SET('Végétarien', 'Végétalien', 'Sans gluten', 'Sans lactose', 'Paleo', 'Keto'),
               type_=sa.String(length=255),
               existing_comment='Régime alimentaire principal',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.alter_column('REGIME_ALIMENTAIRE',
               existing_type=sa.String(length=255),
               type_=mysql.SET('Végétarien', 'Végétalien', 'Sans gluten', 'Sans lactose', 'Paleo', 'Keto'),
               existing_comment='Régime alimentaire principal',
               existing_nullable=True)
        batch_op.alter_column('BIO',
               existing_type=mysql.TEXT(),
               comment='Description de l utilisateur',
               existing_comment="Description de l'utilisateur",
               existing_nullable=True)
        batch_op.alter_column('AVATAR',
               existing_type=mysql.VARCHAR(length=255),
               comment='Chemin vers limage de profil',
               existing_comment="Chemin vers l'image de profil",
               existing_nullable=True)
        batch_op.drop_column('IS_ADMIN')

    with op.batch_alter_table('recette_ingredient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('recette', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('regime_alimentaire',
               existing_type=sa.String(length=255),
               type_=mysql.SET('Végétarien', 'Végétalien', 'Sans gluten', 'Sans lactose', 'Paleo', 'Keto'),
               existing_nullable=True)

    with op.batch_alter_table('preference_utilisateur', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('NOTE',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=False)

    with op.batch_alter_table('historique_recherche', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('historique_consultation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('favoris', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('commentaire', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('collection_recette', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
